services:
  fsm:
    build:
      context: .
      target: final
    env_file:
      - ./.env
    ports:
      - "$HTTP_PORT:$HTTP_PORT"

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$MONGO_USER"
      MONGO_INITDB_ROOT_PASSWORD: "$MONGO_PASS"
      MONGO_INITDB_DATABASE: "$MONGO_DB"
